name: gh-pages

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          DENO_INSTALL: /home/runner/.deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
          deno upgrade --version 1.8.0
          deno install --unstable --allow-env --allow-read --allow-write --allow-net --allow-run -n pagic https://deno.land/x/pagic@v1.2.0/mod.ts
          pagic build

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GA_ID: UA-169223577-1
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: deno-tutorial.js.org

  build-and-deploy-cn:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build CN
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          DENO_INSTALL: /home/runner/.deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
          deno upgrade --version 1.6.3
          deno install --unstable --allow-env --allow-read --allow-write --allow-net --allow-run -n pagic https://deno.land/x/pagic@v1.1.1/mod.ts
          pagic build
    
      - name: Deploy CN
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GA_ID: UA-169621310-1
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: denocn/deno-tutorial
          publish_dir: ./dist
          cname: tutorial.deno.js.cn
